name: Build and Push Docs
on: ["push", "pull_request"]

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Yarn
        run: yarn install
      
      - name: Build Docs 
        run: yarn docs:build

      - name: bundle install
        uses: EndBug/add-and-commit@v7
        with:
          add: 'docs'
          author_name: GH Actions
          default_author: github_actions
          message: 'docs:build from Github Actions'
