name: CI
on: [push]
jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn install
    - run: yarn docs:build
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'docs'
        author_name: GH Actions
        default_author: github_actions
        message: 'docs:build from Github Actions'
        pull: 'NO-PULL or --rebase --autostash ...'
